### ISSUE TITLE
QA: "Patient Added" message on refresh

### ISSUE THREAD

**Issue by glassyeyedfish** [jewbe22/EECS3311-project-group8#62]
Configuration: Running on Linux, Java Version 19
Type: Bug
Can Reproduce: Yes

Problem:
In "Patient Management", when you click "Refresh" without having done anything else in the menu, the message "Patient Added Successfully" is displayed even though I haven't clicked "Add Patient" yet.

Suggested fix:
Ensure that this message is only displayed when a patient is actually added.

**Comment by jewbe22** [comment]
it is fixed
