### ISSUE TITLE
QA: Some text fields can be edited when they shouldn't

### ISSUE THREAD

**Issue by glassyeyedfish** [jewbe22/EECS3311-project-group8#64]
Configuration: Running on Linux, Java Version 19
Type: Bug
Can Reproduce: Yes

Problem:
The following text fields can be edited when they should actually be showing static information:
- The patient table in "Manage Patients"
- Every text field in "See Report"

Suggested fix:
Make these text fields not editable.

**Comment by jewbe22** [comment]
those two fields were set to be editable and now they are not editable. it is fixed
