### ISSUE TITLE
QA: can have a negative number of refills remaining on a prescription

### ISSUE THREAD

**Issue by LJWoolner** [jewbe22/EECS3311-project-group8#72]
Configuration: Running on Windows, Java Version 19
Type: Bug
Can Reproduce: Yes
Problem
When you refill a prescription enough times, the number of refills left can become negative. Here is a screenshot demonstrating an error message that suggests -2 refills remain. 
![image](https://user-images.githubusercontent.com/107645283/225704305-6d897aa8-408c-42c4-b52e-45fa454eb6a8.png)

Suggested fix: add a conditional statement that ensures the number of remaining refills is greater than or equal to zero.

**Comment by minhtto** [comment]
fixed this bug
